from statsautochess.piece.chesspiece import ChessPiece
from statsautochess.piece.ptype import PieceType

PIECE_COLLECTIONS = [
    ChessPiece("月之女祭司", [PieceType.精灵, PieceType.猎人], 1), 
    ChessPiece("月之骑士", [PieceType.精灵, PieceType.骑士], 1),
    ChessPiece("敌法师", [PieceType.精灵, PieceType.恶魔猎手], 1),
    ChessPiece("巫医", [PieceType.巨魔, PieceType.术士], 1),
    ChessPiece("暗影萨满", [PieceType.巨魔, PieceType.萨满], 1),
    ChessPiece("暗影牧师", [PieceType.巨魔, PieceType.牧师], 1),
    ChessPiece("森海飞霞", [PieceType.野兽, PieceType.猎人], 1),
    ChessPiece("魅惑魔女", [PieceType.野兽, PieceType.半人马, PieceType.德鲁伊], 1),
    ChessPiece("水晶室女", [PieceType.人类, PieceType.法师], 1),
    ChessPiece("死亡骑士", [PieceType.亡灵, PieceType.骑士], 1),
    ChessPiece("寒冬飞龙", [PieceType.亡灵, PieceType.龙, PieceType.法师], 1),
    ChessPiece("复仇之魂", [PieceType.亡灵, PieceType.恶魔猎手], 1),
    ChessPiece("斧王", [PieceType.兽人, PieceType.战士], 1),
    ChessPiece("赏金猎人", [PieceType.地精, PieceType.刺客], 1),
    ChessPiece("发条技师", [PieceType.地精, PieceType.发明家], 1),
    ChessPiece("修补匠", [PieceType.地精, PieceType.发明家], 1),
    ChessPiece("山岭巨人", [PieceType.元素, PieceType.战士], 1),
    ChessPiece("天界战神", [PieceType.神, PieceType.战士], 1),
    ChessPiece("裂魂人", [PieceType.牛头人, PieceType.刺客], 1),
    ChessPiece("风行者", [PieceType.精灵, PieceType.猎人], 2),
    ChessPiece("仙女龙", [PieceType.精灵, PieceType.龙, PieceType.法师], 2),
    ChessPiece("先知", [PieceType.精灵, PieceType.德鲁伊], 2),
    ChessPiece("蝙蝠骑士", [PieceType.巨魔, PieceType.猎人], 2),
    ChessPiece("屠夫", [PieceType.亡灵, PieceType.骑士], 2),
    ChessPiece("剑圣", [PieceType.兽人, PieceType.战士], 2),
    ChessPiece("兽王", [PieceType.兽人, PieceType.猎人], 2),
    ChessPiece("伐木机", [PieceType.地精, PieceType.发明家], 2),
    ChessPiece("鱼人夜行者", [PieceType.娜迦, PieceType.刺客], 2),
    ChessPiece("娜迦海妖", [PieceType.娜迦, PieceType.巫师], 2),
    ChessPiece("变体精灵", [PieceType.元素, PieceType.刺客], 2),
    ChessPiece("神谕者", [PieceType.神, PieceType.牧师], 2),
    ChessPiece("熊猫酒仙", [PieceType.熊猫, PieceType.武僧], 2),
    ChessPiece("狙击手", [PieceType.矮人, PieceType.猎人], 2),
    ChessPiece("食人魔魔法师", [PieceType.食人魔, PieceType.法师], 2),
    ChessPiece("混沌骑士", [PieceType.恶魔, PieceType.骑士], 2),
    ChessPiece("恶魔巫师", [PieceType.恶魔, PieceType.巫师], 2),
    ChessPiece("虚空假面", [PieceType.无面, PieceType.刺客], 2),
    ChessPiece("半人马战行者", [PieceType.半人马, PieceType.战士], 2),
    ChessPiece("幻影刺客", [PieceType.精灵, PieceType.刺客], 3),
    ChessPiece("树精卫士", [PieceType.精灵, PieceType.德鲁伊], 3),
    ChessPiece("月之哨卫", [PieceType.精灵, PieceType.武僧], 3),
    ChessPiece("神灵武士", [PieceType.巨魔, PieceType.战士], 3),
    ChessPiece("剧毒术士", [PieceType.野兽, PieceType.虫, PieceType.术士], 3),
    ChessPiece("秀逗魔导士", [PieceType.人类, PieceType.法师], 3),
    ChessPiece("军团指挥官", [PieceType.人类, PieceType.骑士], 3),
    ChessPiece("琼英碧灵", [PieceType.亡灵, PieceType.猎人], 3),
    ChessPiece("不朽尸王", [PieceType.亡灵, PieceType.牧师], 3),
    ChessPiece("鱼人守卫", [PieceType.娜迦, PieceType.战士], 3),
    ChessPiece("闪电幽魂", [PieceType.元素, PieceType.法师], 3),
    ChessPiece("大魔导师", [PieceType.神, PieceType.巫师], 3),
    ChessPiece("沙王", [PieceType.虫, PieceType.刺客], 3),
    ChessPiece("影魔", [PieceType.恶魔, PieceType.术士], 3),
    ChessPiece("灵魂守卫", [PieceType.恶魔, PieceType.恶魔猎手], 3),
    ChessPiece("地卜师", [PieceType.狗头人, PieceType.发明家], 3),
    ChessPiece("隐形刺客", [PieceType.萨满, PieceType.刺客], 3),
    ChessPiece("利爪德鲁伊", [PieceType.野兽, PieceType.德鲁伊], 4),
    ChessPiece("齐天大圣", [PieceType.野兽, PieceType.武僧], 4),
    ChessPiece("海军上将", [PieceType.人类, PieceType.战士], 4),
    ChessPiece("光之守卫", [PieceType.人类, PieceType.法师], 4),
    ChessPiece("龙骑士", [PieceType.人类, PieceType.龙, PieceType.骑士], 4),
    ChessPiece("巫妖", [PieceType.亡灵, PieceType.法师], 4),
    ChessPiece("卓尔游侠", [PieceType.亡灵, PieceType.猎人], 4),
    ChessPiece("上帝之手", [PieceType.兽人, PieceType.牧师], 4),
    ChessPiece("电炎绝手", [PieceType.地精, PieceType.骑士], 4),
    ChessPiece("炼金术士", [PieceType.地精, PieceType.食人魔, PieceType.术士], 4),
    ChessPiece("蛇发女妖", [PieceType.娜迦, PieceType.猎人], 4),
    ChessPiece("育母蜘蛛", [PieceType.虫, PieceType.猎人], 4),
    ChessPiece("末日使者", [PieceType.恶魔, PieceType.战士], 4),
    ChessPiece("撼地神牛", [PieceType.牛头人, PieceType.萨满], 4),
    ChessPiece("半人猛犸", [PieceType.半人马, PieceType.猎人], 4),
]

PIECES_PER_LEVEL = [19, 19, 17, 15, 10]

COPIES_PER_PIECE = [20, 20, 15, 15, 10]

COPIES_PER_PIECE_LG = [24, 24, 18, 18, 12]

DRAW_PROBABILITY = [
    [1.00, 0.00, 0.00, 0.00, 0.00],
    [0.70, 0.30, 0.00, 0.00, 0.00],
    [0.60, 0.35, 0.05, 0.00, 0.00],
    [0.55, 0.40, 0.15, 0.00, 0.00],
    [0.35, 0.40, 0.23, 0.02, 0.00],
    [0.30, 0.33, 0.30, 0.07, 0.00],
    [0.30, 0.30, 0.30, 0.10, 0.00],
    [0.24, 0.25, 0.25, 0.25, 0.01],
    [0.22, 0.30, 0.25, 0.20, 0.03],
    [0.20, 0.22, 0.25, 0.28, 0.05],
]